config/routes.rb
Secretfreesamples::Application.routes.draw do |map|
  namespace :admin do
    match 'clear' => 'dashboard#clear_session'
    resources :styles do
      resources :style_files
    end
    resources :offers
    resources :visits do
      collection do
        get :positions
      end
    end
  end
  
  resources :offers
  
  root :to => 'offers#index'

end

app/models/click.rb
class Click < ActiveRecord::Base
  belongs_to :visit
  belongs_to :offer
  
  scope :converted, lambda {
    where(:converted => true)
  }
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  has_many :clicks
  has_attached_file :banner
  
  validates_presence_of :name
  validates_presence_of :payout
  validates_presence_of :url
  validates_attachment_presence :banner
end

app/models/style.rb
class Style < ActiveRecord::Base
  has_many :style_files
  has_many :visits
  has_many :clicks, :through => :visits
  
  validates_presence_of :name
  validates_presence_of :code
end

app/models/style_file.rb
class StyleFile < ActiveRecord::Base
  belongs_to :style
  has_attached_file :attachment
  validates_attachment_presence :attachment
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :style
  has_many :clicks
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_filter :require_admin
  
  layout 'admin'
  
  def index
    
  end
  
  def clear_session
    session[:visit_id] = nil
    redirect_to('/')
  end
  
  def positions
  end
end

app/controllers/admin/offers_controller.rb
class Admin::OffersController < ApplicationController
  before_filter :require_admin
  
  inherit_resources
  
  layout 'admin'
end

app/controllers/admin/style_files_controller.rb
class Admin::StyleFilesController < ApplicationController
  before_filter :require_admin
  
  inherit_resources
  belongs_to :style
  
  layout 'admin'
  
  def create
    create! { admin_style_style_files_url(@style) }
  end
end

app/controllers/admin/styles_controller.rb
class Admin::StylesController < ApplicationController
  before_filter :require_admin
  
  inherit_resources
  
  layout 'admin'
  
  def create
    create! { admin_styles_url }
  end
  
  def update
    update! { admin_styles_url }
  end
end

app/controllers/admin/visits_controller.rb
class Admin::VisitsController < ApplicationController
  before_filter :require_admin
  
  inherit_resources
  
  layout 'admin'
  
  def positions
    
  end
  
  protected
  
  def collection
    @visits ||= end_of_association_chain.order('created_at desc').limit(100)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
  
  protected
  
  def load_visit
    begin
      @visit = Visit.find(session[:visit_id])
    rescue
      @visit = Visit.create(:ip_address => request.remote_ip, :browser => request.env["HTTP_USER_AGENT"], :referrer_url => request.env["HTTP_REFERER"], :style_id => randomize_array(Style.where(:active => true)).first.id)
      session[:visit_id] = @visit.id
    end
  end
  
  def require_admin
    authenticate_or_request_with_http_basic do |username,password|
      username == "admin" && password = "pass69"
    end
  end
  
  def randomize_array(array)
    array.sort_by { rand }
  end
  
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_filter :load_visit
  
  def index
    @offers = randomize_array(Offer.where(:active => true))
    render :inline => @visit.style.code
  end
  
  def show
    @offer = Offer.find(params[:id])
    click = Click.create(:visit => @visit, :offer => @offer, :position => params[:p])
    redirect_to @offer.url# + "&subid=#{click.id}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/style_files_helper.rb
module StyleFilesHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/admin/offers/_form.html.erb
<%= form_for([:admin,@offer], :html => { :multipart => true }) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :payout %><br />
    <%= f.text_field :payout %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
	<div class="field">
    <%= f.label :banner %><br />
		<% if @offer.banner && @offer.banner.file? %>
			<%= image_tag @offer.banner.url %><br />
			New banner<br />
		<% end %>
    <%= f.file_field :banner %>
  </div>
	<div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/offers/edit.html.erb
<h1>Editing offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/admin/offers/index.html.erb
<h1>Listing offers</h1>

<table class="centerText">
  <tr>
    <th>Name</th>
    <th>Status</th>
    <th>Banner</th>
    <th>Url</th>
		<th>Clicks</th>
		<th>Converted</th>
		<th>Payout</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @offers.each do |offer| %>
  <tr>
    <td><%= offer.name %></td>
		<td><%= offer.active ? "Active" : "Inactive" %></td>
    <td><%= image_tag offer.banner.url, :style => 'max-width: 100px;' %></td>
    <td><%= link_to "Preview", offer.url %></td>
		<td><%= offer.clicks.count %></td>
		<td><%= offer.clicks.converted.count %></td>
		<td><%= number_to_currency offer.payout %></td>
    <td><%= link_to 'View info', [:admin,offer] %></td>
    <td><%= link_to 'Edit', edit_admin_offer_path(offer) %></td>
    <td><%= link_to 'Delete', [:admin,offer], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Offer', new_admin_offer_path %>

app/views/admin/offers/new.html.erb
<h1>New offer</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_offers_path %>

app/views/admin/offers/show.html.erb
<p>
  <b>Name:</b>
  <%= @offer.name %>
</p>

<p>
	<% if @offer.banner && @offer.banner.file? %>
		<b>Banner:</b><br />
		<%= image_tag @offer.banner.url %>
	<% end %>
</p>

<p>
  <b>Payout:</b>
  <%= number_to_currency @offer.payout %>
</p>

<p>
  <b>Active:</b>
  <%= @offer.active ? "Yes" : "No" %>
</p>

<p>
  <b>Url:</b>
  <%= @offer.url %>
</p>
<p>
	<%= link_to 'Edit', edit_admin_offer_path(@offer) %>
</p>
<h2>View stats</h2>
<p>Coming soon.</p>
<p>
	<%= link_to 'Back', admin_offers_path %>
</p>

app/views/admin/style_files/_form.html.erb
<%= form_for([:admin,@style,@style_file], :html => { :multipart => true }) do |f| %>
  <% if @style_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@style_file.errors.count, "error") %> prohibited this style_file from being saved:</h2>

      <ul>
      <% @style_file.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :attachment %><br />
    <%= f.file_field :attachment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/style_files/index.html.erb
<h1>Manage files for &lsquo;<%= @style.name %>&rsquo; style</h1>

<table>
  <tr>
    <th>Image</th>
    <th>Path</th>
    <th></th>
    <th></th>
  </tr>

<% @style_files.each do |style_file| %>
  <tr>
		<td><%= image_tag style_file.attachment.url(nil,false), :style => 'max-height: 100px; max-width: 200px;' %>
    <td><%= style_file.attachment.url(nil,false) %></td>
    <td><%= link_to 'View', style_file.attachment.url(nil,false) %></td>
    <td><%= link_to 'Delete', [:admin,@style,style_file], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Style file', new_admin_style_style_file_path(@style) %>

<p>
	<%= link_to 'Back to styles', admin_styles_path %>
</p>

app/views/admin/style_files/new.html.erb
<h1>New style_file</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_style_style_files_path(@style) %>

app/views/admin/style_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Style:</b>
  <%= @style_file.style_id %>
</p>


<%= link_to 'Edit', edit_style_file_path(@style_file) %> |
<%= link_to 'Back', style_files_path %>

app/views/admin/styles/_form.html.erb
<%= form_for([:admin,@style]) do |f| %>
  <% if @style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
      <% @style.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_area :code %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/styles/edit.html.erb
<h1>Editing style</h1>

<%= render 'form' %>

<p><%= link_to 'Manage files', admin_style_style_files_path(@style) %></p>

<%= link_to 'Back', admin_styles_path %>

app/views/admin/styles/index.html.erb
<h1>Listing styles</h1>

<table class="centerText">
  <tr>
    <th>Name</th>
    <th>Active?</th>
		<th>Clicks</th>
		<th>Conversions</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @styles.each do |style| %>
  <tr>
    <td><%= style.name %></td>
    <td><%= style.active ? "Yes" : "No" %></td>
		<td><%= style.clicks.count %></td>
		<td><%= style.clicks.converted.count %></td>
    <td><%= link_to 'Manage files', admin_style_style_files_path(style) %></td>
    <td><%= link_to 'Edit code', edit_admin_style_path(style) %></td>
    <td><%= link_to 'Delete', [:admin,style], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Style', new_admin_style_path %>

app/views/admin/styles/new.html.erb
<h1>New style</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_styles_path %>

app/views/admin/visits/index.html.erb
<h1>Visitor stats</h1>

<h2>Latest visitors</h2>
<table class="centerText">
	<tr>
		<th>Time</th>
		<th>Style</th>
		<th>Clicks</th>
		<th>Conversions</th>
		<th>Referring URL</th>
	</tr>
	<% @visits.each do |visit| %>
		<tr>
			<td><%= visit.created_at.strftime('%m/%d/%y %H:%M')%></td>
			<td><%= visit.style ? visit.style.name : "None" %></td>
			<td><%= visit.clicks.count %></td>
			<td><%= visit.clicks.converted.count %></td>
			<td><%= visit.referrer_url %></td>
		</tr>
	<% end %>
</table>

app/views/admin/visits/positions.html.erb
<% (1..15).each do |i| %>
	<div style="float: left; width: 30%; margin-right: 10px; height: 150px; line-height: 150px; font-size: 30px; text-align: center;">
		<%= Click.where(:position => i).count %> / <%= Click.where(:position => i).converted.count %>
	</div>
<% end %>

<br style="clear: both;" />

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Secretfreesamples</title>
  <%= stylesheet_link_tag 'admin' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body><div id="content">
	<h1 id="title">Secret Free Samples Control Panel</h1>
	<div id="nav"><%= render_navigation %></div>
	<br style="clear: both;">
	<div id="notice"><%= notice %> <%= alert %></div>
	<%= yield %>
</div></body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Secretfreesamples</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<p id="notice"><%= notice %> <%= alert %></p>
<%= yield %>

</body>
</html>

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :payout %><br />
    <%= f.text_field :payout %>
  </div>
  <div class="field">
    <%= f.label :network_id %><br />
    <%= f.text_field :network_id %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/_offers_with_images.html.erb
<ul id="offers">
	<% position = 1 %>
	<% @offers.each do |offer| %>
		<li><%= link_to image_tag(offer.banner.url, :alt => offer.name), offer_path(offer, :p => position) %></li>
		<% position += 1 %>
	<% end %>
</ul>

app/views/offers/edit.html.erb
<h1>Editing offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<h1>Listing offers</h1>

Visit id: <%= @visit.id %>

<table>
  <tr>
    <th>Name</th>
    <th>Payout</th>
    <th>Network</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @offers.each do |offer| %>
  <tr>
    <td><%= offer.name %></td>
    <td><%= offer.payout %></td>
    <td><%= offer.network_id %></td>
    <td><%= offer.url %></td>
    <td><%= link_to 'Show', offer %></td>
    <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
    <td><%= link_to 'Destroy', offer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<h1>New offer</h1>

<%= render 'form' %>

<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @offer.name %>
</p>

<p>
  <b>Payout:</b>
  <%= @offer.payout %>
</p>

<p>
  <b>Network:</b>
  <%= @offer.network_id %>
</p>

<p>
  <b>Url:</b>
  <%= @offer.url %>
</p>


<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>